apiVersion: v2
name: pagerduty-exporter
type: application
description: A Helm chart for pagerduty-exporter
home: https://github.com/webdevops/pagerduty-exporter
version: 1.1.4
# renovate: image=webdevops/pagerduty-exporter
appVersion: 24.9.0
keywords:
- pagerduty-exporter
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/pagerduty-exporter/
