apiVersion: v2
name: azure-resourcemanager-exporter
type: application
description: A Helm chart for azure-resourcemanager-exporter
home: https://github.com/webdevops/azure-resourcemanager-exporter
version: 1.2.0
# renovate: image=webdevops/azure-resourcemanager-exporter
appVersion: 23.6.0
keywords:
- azure-resourcemanager-exporter
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/azure-resourcemanager-exporter/
