apiVersion: v2
name: azure-resourcegraph-exporter
type: application
description: A Helm chart for azure-resourcegraph-exporter
home: https://github.com/webdevops/azure-resourcegraph-exporter
version: 1.1.5
# renovate: image=webdevops/azure-resourcegraph-exporter
appVersion: 25.12.0
keywords:
- azure-resourcegraph-exporter
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/azure-resourcegraph-exporter/
