apiVersion: v2
name: azure-scheduledevents-manager
type: application
description: A Helm chart for azure-scheduledevents-manager
home: https://github.com/webdevops/azure-scheduledevents-manager
version: 1.0.14
# renovate: image=webdevops/azure-scheduledevents-exporter
appVersion: 24.9.0
keywords:
  - azure-scheduledevents-manager
maintainers:
  - email: mblaschke82@gmail.com
    name: mblaschke
sources:
  - https://github.com/webdevops/azure-scheduledevents-manager/
