apiVersion: v2
name: azure-janitor
type: application
description: A Helm chart for azure-janitor
home: https://github.com/webdevops/azure-janitor
version: 1.0.7
# renovate: image=webdevops/azure-janitor
appVersion: 22.9.0
keywords:
- azure-janitor
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/azure-janitor/
