apiVersion: v2
name: kube-pool-manager
type: application
description: A Helm chart for kube-pool-manager
home: https://github.com/webdevops/kube-pool-manager
version: 1.0.10
# renovate: image=webdevops/kube-pool-manager
appVersion: 22.9.0
keywords:
  - kube-pool-manager
maintainers:
  - email: mblaschke82@gmail.com
    name: mblaschke
sources:
  - https://github.com/webdevops/kube-pool-manager/
