apiVersion: v2
name: azure-keyvault-exporter
type: application
description: A Helm chart for azure-keyvault-exporter
home: https://github.com/webdevops/azure-keyvault-exporter
version: 1.0.0
appVersion: 22.9.0
keywords:
- azure-keyvault-exporter
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/azure-keyvault-exporter/

