---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "azure-keyvault-exporter.fullname" . }}
  namespace: {{ template "azure-keyvault-exporter.namespace" . }}
  labels:
{{ include "azure-keyvault-exporter.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      appProtocol: http
  selector: {{- include "azure-keyvault-exporter.selectorLabels" . | nindent 4 }}
